### PR TITLE
!!changelog: Allow specifying branch & fix fail cases

### LINKED ISSUE #89: Improve changelog to get last commit from specified branch
Currently !!changelog gets the last commit from the **master** of given repo and the usage is like:
`!!changelog ekinhbayar/Jeeves`
We could use the master by default but if a `$command->getParameter(1)` is given and is a valid branch, use that instead. 
ie. `!!changelog ekinhbayar/Jeeves fix/changelog` would get [this](https://api.github.com/repos/ekinhbayar/jeeves/git/refs/heads/fix/changelog) as a result set.

### PR DESCRIPTION
**Pull request by ekinhbayar**
Allows specifying a branch to get the latest commit from and fixes catchable fatal error if it cannot retrieve sha. Below is now valid.
`!!changelog ekinhbayar/Jeeves fix/changelog`

Closes #89

### CODE REVIEW

File: src/Plugins/Changelog.php [hunk 1]
```diff
@@ -33,35 +36,40 @@ public function changelog(Command $command): \Generator {
...
+            . urlencode($repo) . '/git/refs/heads/'
+            . urlencode($branch)
         );
 
         if ($response->getStatus() !== 200) {
-            return $this->chatClient->postMessage($command->getRoom(), "Failed to fetch repo for $path");
+            throw new ReferenceNotFoundException("Failed to fetch repository for $path");
         }
 
         $json = json_decode($response->getBody());
```
Comment (PeeHaa) [inline src/Plugins/Changelog.php]: $commit = json_decode($response->getBody(), true);

File: src/Plugins/Changelog.php [hunk 2]
```diff
@@ -33,35 +36,40 @@ public function changelog(Command $command): \Generator {
...
-        if (!isset($json->object->sha)) {
-            return $this->chatClient->postMessage($command->getRoom(), "Failed to fetch reference SHA for $path");
+        $sha  = $json->object->sha ?? false;
```
Comment (PeeHaa) [inline src/Plugins/Changelog.php]: This can be removed

File: src/Plugins/Changelog.php [hunk 3]
```diff
@@ -33,35 +36,40 @@ public function changelog(Command $command): \Generator {
...
+
+        if (!$sha) {
```
Comment (PeeHaa) [inline src/Plugins/Changelog.php]: if (isset(!$commit['object'])) {

File: src/Plugins/Changelog.php [hunk 4]
```diff
@@ -33,35 +36,40 @@ public function changelog(Command $command): \Generator {
...
+            throw new ReferenceNotFoundException("Failed to fetch reference SHA for $path");
         }
 
-        return $json->object->sha;
+        return $sha;
```
Comment (PeeHaa) [inline src/Plugins/Changelog.php]: return $commit['object']['sha'];
